### ISSUE TITLE
Output yang di keluarkan membingungkan

### ISSUE THREAD

**Issue by InterestFD** [fugoou/optimize#1]
Setelah menjalankan di termux dengan bantuan shizuku.
hasil yang keluar hanya
"_/data/local/tmp/daemon: l�_"
dan ketika mencobanya di brevent, output yang sama keluar.. tampak nya ini memang ditolak vendor hp ku_- sayang bett

**Comment by fugoou** [comment]
iyakah, issue gini banyak banget gtw gw apa solusinya, mangkanya gw open discuss, emang masalah vendor ya?

**Comment by fugoou** [comment]
padahal gw run di terminal mt manager aman aman aja

**Comment by InterestFD** [comment]
> iyakah, issue gini banyak banget gtw gw apa solusinya, mangkanya gw open discuss, emang masalah vendor ya?

kyk nya sih iya, masalah vendor ini.. vendor sialan

**Comment by InterestFD** [comment]
dah, udh bagus kok module mu bang, tinggal hoki2an vendor aja, thanks

**Comment by fugoou** [comment]
bukan masalah vendor, masalah architecture ternyata https://github.com/fugoou/optimize#information

**Comment by fugoou** [comment]
udah support 64 bit, open source no enc nih
